// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://facgdpqsepiqaefudhnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhY2dkcHFzZXBpcWFlZnVkaG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzI5NjQsImV4cCI6MjA1Njg0ODk2NH0.jOgedFoJrIILxdTWszQQ1rIJd-wV1Km1kG89bQvlFQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);